# Generated by Django 4.0.4 on 2023-03-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=1000)),
                ('photo_link', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('main_topic', models.CharField(max_length=64)),
            ],
        ),
    ]
